// src/react/components/Table/cells/ColorCell.tsx
import type { ColorColumnSchema } from '../../../../shared/types/schema';

interface CellProps {
    schema: ColorColumnSchema;
    value: unknown;
    record: Record<string, unknown>;
}

export function ColorCell({ value }: CellProps) {
    if (!value) {
        return <span className="text-s-text-faint">—</span>;
    }

    const color = String(value);

    return (
        <div className="flex items-center gap-2">
            <span
                className="inline-block h-5 w-5 shrink-0 rounded-full border border-s-border"
                style={{ backgroundColor: color }}
                aria-label={color}
            />
            <span className="text-xs text-s-text-muted">{color}</span>
        </div>
    );
}

// src/vue/components/Table/cells/ColorCell.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { ColorColumnSchema } from '../../../../shared/types/schema';

const props = defineProps<{
    schema: ColorColumnSchema;
    value: unknown;
}>();

const color = computed(() => (props.value ? String(props.value) : ''));
</script>

<template>
    <span v-if="!value" class="text-s-text-faint">—</span>
    <div v-else class="flex items-center gap-2">
        <span
            class="inline-block h-5 w-5 shrink-0 rounded-full border border-s-border"
            :style="{ backgroundColor: color }"
            :aria-label="color"
        />
        <span class="text-xs text-s-text-muted">{{ color }}</span>
    </div>
</template>
