// src/vue/components/Infolist/entries/ImageEntry.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '../../../../shared/utils/cn';
import type { ImageDetailSchema } from '../../../../shared/types/schema';

const props = defineProps<{
    schema: ImageDetailSchema;
    value: unknown;
}>();

const src = computed(() => (props.value ? String(props.value) : ''));
const width = computed(() => props.schema.width ?? '80px');
const height = computed(() => props.schema.height ?? '80px');
</script>

<template>
    <span v-if="!value" class="text-sm text-s-text-faint">--</span>
    <img
        v-else
        :src="src"
        alt=""
        :class="cn(
            'object-cover',
            schema.circular ? 'rounded-full' : 'rounded-lg',
        )"
        :style="{ width, height }"
        loading="lazy"
    />
</template>

// src/react/components/Infolist/entries/ImageEntry.tsx
import { cn } from '../../../../shared/utils/cn';
import type { ImageDetailSchema } from '../../../../shared/types/schema';

interface EntryProps {
    schema: ImageDetailSchema;
    value: unknown;
}

export function ImageEntry({ schema, value }: EntryProps) {
    if (!value) {
        return <span className="text-sm text-s-text-faint">--</span>;
    }

    const src = String(value);
    const width = schema.width ?? '80px';
    const height = schema.height ?? '80px';

    return (
        <img
            src={src}
            alt=""
            className={cn(
                'object-cover',
                schema.circular ? 'rounded-full' : 'rounded-lg',
            )}
            style={{ width, height }}
            loading="lazy"
        />
    );
}
