// src/vue/components/Form/fields/SlugField.vue
<script setup lang="ts">
import { cn } from '../../../../shared/utils/cn';
import type { SlugFieldSchema } from '../../../../shared/types/schema';
import { inputClasses } from './_shared';

interface Props {
    schema: SlugFieldSchema;
    value: string | null;
    error?: string | null;
}

defineProps<Props>();
const emit = defineEmits<{ change: [value: string] }>();
</script>

<template>
    <div>
        <div class="flex">
            <span v-if="schema.prefix" class="inline-flex items-center rounded-l-lg border border-r-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted">{{ schema.prefix }}</span>
            <input
                :id="schema.name"
                type="text"
                :value="value ?? ''"
                :placeholder="schema.placeholder ?? undefined"
                :disabled="schema.disabled"
                :class="cn(
                    inputClasses,
                    schema.prefix && 'rounded-l-none',
                    schema.suffix && 'rounded-r-none',
                    error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
                )"
                @input="emit('change', ($event.target as HTMLInputElement).value)"
            />
            <span v-if="schema.suffix" class="inline-flex items-center rounded-r-lg border border-l-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted">{{ schema.suffix }}</span>
        </div>
        <p class="mt-1 text-xs text-s-text-faint">
            Auto-generated from <span class="font-medium">{{ schema.from }}</span>
        </p>
    </div>
</template>

// src/react/components/Form/fields/SlugField.tsx
import { cn } from '../../../../shared/utils/cn';
import type { SlugFieldSchema } from '../../../../shared/types/schema';

interface SlugFieldProps {
    schema: SlugFieldSchema;
    value: string;
    onChange: (value: string) => void;
    error?: string | null;
}

const inputClasses =
    'w-full rounded-lg border border-s-border-strong bg-s-input px-3 py-2 text-sm text-s-text focus:border-s-accent focus:ring-1 focus:ring-s-accent/30 disabled:opacity-50 disabled:cursor-not-allowed';

export function SlugField({ schema, value, onChange, error }: SlugFieldProps) {
    return (
        <div>
            <div className="flex">
                {schema.prefix && (
                    <span className="inline-flex items-center rounded-l-studio border border-r-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted">
                        {schema.prefix}
                    </span>
                )}
                <input
                    id={schema.name}
                    type="text"
                    value={value ?? ''}
                    onChange={(e) => onChange(e.target.value)}
                    placeholder={schema.placeholder ?? undefined}
                    disabled={schema.disabled}
                    className={cn(
                        inputClasses,
                        schema.prefix && 'rounded-l-none',
                        schema.suffix && 'rounded-r-none',
                        error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
                    )}
                />
                {schema.suffix && (
                    <span className="inline-flex items-center rounded-r-studio border border-l-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted">
                        {schema.suffix}
                    </span>
                )}
            </div>
            <p className="mt-1 text-xs text-s-text-faint">
                Auto-generated from <span className="font-medium">{schema.from}</span>
            </p>
        </div>
    );
}
