// src/react/components/Table/filters/DateFilter.tsx
import { DateRangePicker } from '../../DatePicker';
import type { DateFilterSchema } from '../../../../shared/types/schema';

interface FilterProps {
    schema: DateFilterSchema;
    value: unknown;
    onChange: (value: unknown) => void;
}

export function DateFilter({ schema, value, onChange }: FilterProps) {
    const range = value as { from: string | null; to: string | null } | null;

    return (
        <div className="flex flex-col gap-1.5">
            <span className="text-xs font-medium text-s-text-muted">{schema.label}</span>
            <DateRangePicker
                value={range}
                onChange={onChange}
            />
        </div>
    );
}

// src/vue/components/Table/filters/DateFilter.vue
<script setup lang="ts">
import { computed } from 'vue';
import DateRangePicker from '../../DatePicker/DateRangePicker.vue';
import type { DateFilterSchema } from '../../../../shared/types/schema';

const props = defineProps<{
    schema: DateFilterSchema;
    value: unknown;
}>();

const emit = defineEmits<{ change: [value: unknown] }>();

const range = computed(() => (props.value as { from: string | null; to: string | null } | null) ?? null);

function handleUpdate(v: { from: string | null; to: string | null } | null) {
    emit('change', v);
}
</script>

<template>
    <div class="flex flex-col gap-1.5">
        <span class="text-xs font-medium text-s-text-muted">{{ schema.label }}</span>
        <DateRangePicker
            :model-value="range"
            @update:model-value="handleUpdate"
        />
    </div>
</template>
