// src/react/components/Form/fields/HiddenField.tsx
import type { HiddenFieldSchema } from '../../../../shared/types/schema';

interface HiddenFieldProps {
    schema: HiddenFieldSchema;
    value: unknown;
    onChange: (value: unknown) => void;
    error?: string | null;
}

export function HiddenField({ schema, value }: HiddenFieldProps) {
    return (
        <input
            id={schema.name}
            type="hidden"
            name={schema.name}
            value={String(value ?? '')}
        />
    );
}

// src/vue/components/Form/fields/HiddenField.vue
<script setup lang="ts">
import type { HiddenFieldSchema } from '../../../../shared/types/schema';

interface Props {
    schema: HiddenFieldSchema;
    value: unknown;
    error?: string | null;
}

defineProps<Props>();
defineEmits<{ change: [value: unknown] }>();
</script>

<template>
    <input type="hidden" :name="schema.name" :value="String(value ?? '')" />
</template>
