// src/react/components/Form/fields/PasswordField.tsx
import { useState } from 'react';
import { cn } from '../../../../shared/utils/cn';
import type { PasswordFieldSchema } from '../../../../shared/types/schema';

interface PasswordFieldProps {
    schema: PasswordFieldSchema;
    value: string;
    onChange: (value: string) => void;
    error?: string | null;
}

const inputClasses =
    'w-full rounded-lg border border-s-border-strong bg-s-input px-3 py-2 text-sm text-s-text focus:border-s-accent focus:ring-1 focus:ring-s-accent/30 disabled:opacity-50 disabled:cursor-not-allowed';

export function PasswordField({ schema, value, onChange, error }: PasswordFieldProps) {
    const [revealed, setRevealed] = useState(false);

    return (
        <div className="relative">
            <input
                id={schema.name}
                type={revealed ? 'text' : 'password'}
                value={value ?? ''}
                onChange={(e) => onChange(e.target.value)}
                placeholder={schema.placeholder ?? undefined}
                disabled={schema.disabled}
                className={cn(
                    inputClasses,
                    schema.revealable && 'pr-10',
                    error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
                )}
            />
            {schema.revealable && (
                <button
                    type="button"
                    onClick={() => setRevealed((prev) => !prev)}
                    className="absolute inset-y-0 right-0 flex items-center pr-3 text-s-text-faint hover:text-s-text-muted"
                    aria-label={revealed ? 'Hide password' : 'Show password'}
                >
                    {revealed ? (
                        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.242 4.242L9.88 9.88" />
                        </svg>
                    ) : (
                        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                        </svg>
                    )}
                </button>
            )}
        </div>
    );
}

// src/vue/components/Form/fields/PasswordField.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '../../../../shared/utils/cn';
import type { PasswordFieldSchema } from '../../../../shared/types/schema';
import { inputClasses } from './_shared';

interface Props {
    schema: PasswordFieldSchema;
    value: string | null;
    error?: string | null;
}

defineProps<Props>();
const emit = defineEmits<{ change: [value: string] }>();

const revealed = ref(false);
</script>

<template>
    <div class="relative">
        <input
            :id="schema.name"
            :type="revealed ? 'text' : 'password'"
            :value="value ?? ''"
            :placeholder="schema.placeholder ?? undefined"
            :disabled="schema.disabled"
            :class="cn(
                inputClasses,
                schema.revealable && 'pr-10',
                error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
            )"
            @input="emit('change', ($event.target as HTMLInputElement).value)"
        />
        <button
            v-if="schema.revealable"
            type="button"
            class="absolute inset-y-0 right-0 flex items-center pr-3 text-s-text-faint hover:text-s-text-muted"
            :aria-label="revealed ? 'Hide password' : 'Show password'"
            @click="revealed = !revealed"
        >
            <svg v-if="revealed" class="h-4 w-4" fill="none" viewBox="0 0 24 24" :stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.242 4.242L9.88 9.88" />
            </svg>
            <svg v-else class="h-4 w-4" fill="none" viewBox="0 0 24 24" :stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
            </svg>
        </button>
    </div>
</template>
