// src/react/components/Form/fields/PlaceholderField.tsx
import type { PlaceholderFieldSchema } from '../../../../shared/types/schema';

interface PlaceholderFieldProps {
    schema: PlaceholderFieldSchema;
    value: unknown;
    onChange: (value: unknown) => void;
    error?: string | null;
}

export function PlaceholderField({ schema }: PlaceholderFieldProps) {
    return (
        <div className="rounded-lg bg-s-bg px-3 py-2 text-sm text-s-text-muted">
            {schema.content}
        </div>
    );
}

// src/vue/components/Form/fields/PlaceholderField.vue
<script setup lang="ts">
import type { PlaceholderFieldSchema } from '../../../../shared/types/schema';

interface Props {
    schema: PlaceholderFieldSchema;
    value: unknown;
    error?: string | null;
}

defineProps<Props>();
defineEmits<{ change: [value: unknown] }>();
</script>

<template>
    <div class="rounded-lg bg-s-bg px-3 py-2 text-sm text-s-text-muted">{{ schema.content }}</div>
</template>
