// src/react/components/Form/fields/TextareaField.tsx
import { useCallback, useRef } from 'react';
import { cn } from '../../../../shared/utils/cn';
import type { TextareaFieldSchema } from '../../../../shared/types/schema';

interface TextareaFieldProps {
    schema: TextareaFieldSchema;
    value: string;
    onChange: (value: string) => void;
    error?: string | null;
}

const inputClasses =
    'w-full rounded-lg border border-s-border-strong bg-s-input px-3 py-2 text-sm text-s-text focus:border-s-accent focus:ring-1 focus:ring-s-accent/30 disabled:opacity-50 disabled:cursor-not-allowed';

export function TextareaField({ schema, value, onChange, error }: TextareaFieldProps) {
    const textareaRef = useRef<HTMLTextAreaElement>(null);

    const handleChange = useCallback(
        (e: React.ChangeEvent<HTMLTextAreaElement>) => {
            onChange(e.target.value);

            if (schema.autosize && textareaRef.current) {
                textareaRef.current.style.height = 'auto';
                textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
            }
        },
        [onChange, schema.autosize],
    );

    return (
        <div className="relative">
            <textarea
                id={schema.name}
                ref={textareaRef}
                value={value ?? ''}
                onChange={handleChange}
                placeholder={schema.placeholder ?? undefined}
                disabled={schema.disabled}
                rows={schema.rows}
                maxLength={schema.maxLength ?? undefined}
                className={cn(
                    inputClasses,
                    schema.autosize && 'resize-none overflow-hidden',
                    error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
                )}
            />
            {schema.maxLength !== null && (
                <span className="absolute bottom-2 right-2 text-xs text-s-text-faint">
                    {(value ?? '').length}/{schema.maxLength}
                </span>
            )}
        </div>
    );
}

// src/vue/components/Form/fields/TextareaField.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cn } from '../../../../shared/utils/cn';
import type { TextareaFieldSchema } from '../../../../shared/types/schema';
import { inputClasses } from './_shared';

interface Props {
    schema: TextareaFieldSchema;
    value: string | null;
    error?: string | null;
}

const props = defineProps<Props>();
const emit = defineEmits<{ change: [value: string] }>();

const textareaRef = ref<HTMLTextAreaElement | null>(null);

function handleChange(e: Event) {
    const target = e.target as HTMLTextAreaElement;
    emit('change', target.value);

    if (props.schema.autosize && textareaRef.value) {
        textareaRef.value.style.height = 'auto';
        textareaRef.value.style.height = `${textareaRef.value.scrollHeight}px`;
    }
}
</script>

<template>
    <div class="relative">
        <textarea
            :id="schema.name"
            ref="textareaRef"
            :value="value ?? ''"
            :placeholder="schema.placeholder ?? undefined"
            :disabled="schema.disabled"
            :rows="schema.rows"
            :maxlength="schema.maxLength ?? undefined"
            :class="cn(
                inputClasses,
                schema.autosize && 'resize-none overflow-hidden',
                error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
            )"
            @input="handleChange"
        />
        <span v-if="schema.maxLength !== null" class="absolute bottom-2 right-2 text-xs text-s-text-faint">{{ (value ?? '').length }}/{{ schema.maxLength }}</span>
    </div>
</template>
