// src/react/components/Form/fields/TextField.tsx
import { cn } from '../../../../shared/utils/cn';
import type { TextFieldSchema } from '../../../../shared/types/schema';

interface TextFieldProps {
    schema: TextFieldSchema;
    value: string;
    onChange: (value: string) => void;
    error?: string | null;
}

const inputClasses =
    'w-full rounded-lg border border-s-border-strong bg-s-input px-3 py-2 text-sm text-s-text focus:border-s-accent focus:ring-1 focus:ring-s-accent/30 disabled:opacity-50 disabled:cursor-not-allowed';

export function TextField({ schema, value, onChange, error }: TextFieldProps) {
    const showCounter = schema.maxLength !== null;

    return (
        <div className="relative">
            <div className="flex">
                {schema.prefix && (
                    <span className="inline-flex items-center rounded-l-studio border border-r-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted">
                        {schema.prefix}
                    </span>
                )}
                <input
                    id={schema.name}
                    type="text"
                    value={value ?? ''}
                    onChange={(e) => onChange(e.target.value)}
                    placeholder={schema.placeholder ?? undefined}
                    disabled={schema.disabled}
                    maxLength={schema.maxLength ?? undefined}
                    minLength={schema.minLength ?? undefined}
                    className={cn(
                        inputClasses,
                        schema.prefix && 'rounded-l-none',
                        schema.suffix && 'rounded-r-none',
                        error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
                    )}
                />
                {schema.suffix && (
                    <span className="inline-flex items-center rounded-r-studio border border-l-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted">
                        {schema.suffix}
                    </span>
                )}
            </div>
            {showCounter && (
                <span className="absolute bottom-1 right-2 text-xs text-s-text-faint">
                    {(value ?? '').length}/{schema.maxLength}
                </span>
            )}
        </div>
    );
}

// src/vue/components/Form/fields/TextField.vue
<script setup lang="ts">
import { cn } from '../../../../shared/utils/cn';
import type { TextFieldSchema } from '../../../../shared/types/schema';
import { inputClasses } from './_shared';

interface Props {
    schema: TextFieldSchema;
    value: string | null;
    error?: string | null;
}

defineProps<Props>();
const emit = defineEmits<{ change: [value: string] }>();
</script>

<template>
    <div class="relative">
        <div class="flex">
            <span
                v-if="schema.prefix"
                class="inline-flex items-center rounded-l-lg border border-r-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted"
            >{{ schema.prefix }}</span>
            <input
                :id="schema.name"
                type="text"
                :value="value ?? ''"
                :placeholder="schema.placeholder ?? undefined"
                :disabled="schema.disabled"
                :maxlength="schema.maxLength ?? undefined"
                :minlength="schema.minLength ?? undefined"
                :class="cn(
                    inputClasses,
                    schema.prefix && 'rounded-l-none',
                    schema.suffix && 'rounded-r-none',
                    error && 'border-red-500 focus:border-red-500 focus:ring-red-500',
                )"
                @input="emit('change', ($event.target as HTMLInputElement).value)"
            />
            <span
                v-if="schema.suffix"
                class="inline-flex items-center rounded-r-lg border border-l-0 border-s-border-strong bg-s-bg px-3 text-sm text-s-text-muted"
            >{{ schema.suffix }}</span>
        </div>
        <span
            v-if="schema.maxLength !== null"
            class="absolute bottom-1 right-2 text-xs text-s-text-faint"
        >{{ (value ?? '').length }}/{{ schema.maxLength }}</span>
    </div>
</template>
