// src/react/components/Infolist/entries/MoneyEntry.tsx
import { formatMoney } from '../../../../shared/utils/formatters';
import type { MoneyDetailSchema } from '../../../../shared/types/schema';

interface EntryProps {
    schema: MoneyDetailSchema;
    value: unknown;
}

export function MoneyEntry({ schema, value }: EntryProps) {
    if (value == null) {
        return <span className="text-sm text-s-text-faint">--</span>;
    }

    const numericValue = Number(value);
    if (isNaN(numericValue)) {
        return <span className="text-sm text-s-text-faint">--</span>;
    }

    const formatted = formatMoney(numericValue, schema.currency, schema.locale ?? undefined);

    return (
        <span className="text-sm tabular-nums text-s-text">
            {formatted}
        </span>
    );
}

// src/vue/components/Infolist/entries/MoneyEntry.vue
<script setup lang="ts">
import { computed } from 'vue';
import { formatMoney } from '../../../../shared/utils/formatters';
import type { MoneyDetailSchema } from '../../../../shared/types/schema';

const props = defineProps<{
    schema: MoneyDetailSchema;
    value: unknown;
}>();

const numericValue = computed(() => (props.value == null ? NaN : Number(props.value)));
const isInvalid = computed(() => props.value == null || isNaN(numericValue.value));
const formatted = computed(() => formatMoney(numericValue.value, props.schema.currency, props.schema.locale ?? undefined));
</script>

<template>
    <span v-if="isInvalid" class="text-sm text-s-text-faint">--</span>
    <span v-else class="text-sm tabular-nums text-s-text">
        {{ formatted }}
    </span>
</template>
